kind: Component
resources:
  - res
patches:
  - target:
      kind: Ingress
    patch: |
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/name
        value: trieve-keycloak
