name: Update release PR and create release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    runs-on: blacksmith-2vcpu-ubuntu-2204
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release Please
        id: release-please
        uses: googleapis/release-please-action@v4

  publish-manifest:
    needs:
      - release-please
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    permissions:
      contents: write
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.29.1"
      - name: Build Manifests
        run: |
          kubectl kustomize glasskube/trieve > glasskube/manifest.yaml
          kubectl kustomize glasskube/trieve-aws > glasskube/trieve-aws.yaml
      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
        run: gh release upload ${{ needs.release-please.outputs.tag_name }} glasskube/manifest.yaml glasskube/trieve-aws.yaml
